### ISSUE TITLE
Error when running on OSX

### ISSUE THREAD

**Issue by waynestallwood-kcom** [KCOM-Enterprise/cfn-square#4]
When running CFN-Square with a known good yaml I get the following on OSX

29.09.2017 14:35:26 ERROR: Failed with unexpected error
29.09.2017 14:35:26 ERROR: 'module' object has no attribute 'topological_sort_recursive'
Traceback (most recent call last):
  File "/Users/wstallwood/Library/Python/2.7/lib/python/site-packages/cfn_sphere/cli.py", line 152, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/Users/wstallwood/Library/Python/2.7/lib/python/site-packages/cfn_sphere/__init__.py", line 82, in create_or_update_stacks
    stack_processing_order = DependencyResolver().get_stack_order(desired_stacks)
  File "/Users/wstallwood/Library/Python/2.7/lib/python/site-packages/cfn_sphere/stack_configuration/dependency_resolver.py", line 77, in get_stack_order
    order = networkx.topological_sort_recursive(graph)
AttributeError: 'module' object has no attribute 'topological_sort_recursive'
29.09.2017 14:35:26 INFO: Please report at https://github.com/KCOM-Enterprise/cfn-square/issues!

**Comment by rayoogmy** [comment]
https://github.com/KCOM-Enterprise/cfn-square/pull/3 should fix it
